name: CI

env:
  protoc_version: '3.x'

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  deploy_github_linux:
    name: "Deploy Github: Linux"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with: { version: "${{ env.protoc_version }}", repo-token: "${{ github.token }}" }
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart pub run grinder protobuf
      - name: Compile
        run: dart pub run grinder pkg-compile-snapshot
        env: {GH_BEARER_TOKEN: "${{ github.token }}"}
      - name: Upload binaries to tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/dart-sass-embedded.snapshot
          asset_name: dart-sass-embedded.snapshot
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"

