name: CI

env:
  protoc_version: '3.x'

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  dart_tests:
    name: "Dart tests | Dart ${{ matrix.dart_channel }} | ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dart_channel: [stable]
        include: [{os: ubuntu-latest, dart_channel: dev}]

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with: { version: "${{ env.protoc_version }}", repo-token: "${{ github.token }}" }
      - uses: dart-lang/setup-dart@v1
        with: {sdk: "${{ matrix.dart_channel }}"}

      - name: Check out Dart Sass
        uses: sass/clone-linked-repo@v1
        with:
          repo: sass/dart-sass
          path: build/dart-sass
          default-ref: null

      - name: Add Dart Sass to pubspec
        run: |
          if [[ -d build/dart-sass ]]; then
            (
              echo "dependency_overrides:"
              echo "  sass: {path: build/dart-sass}"
              echo "  sass_api: {path: build/dart-sass/pkg/sass_api}"
            ) >> pubspec.yaml
          fi
        shell: bash

      - name: Check out embedded Sass protocol
        uses: sass/clone-linked-repo@v1
        with: {repo: sass/embedded-protocol, path: build/embedded-protocol}

      - run: dart pub get
      - run: dart pub run grinder protobuf
        env: {UPDATE_SASS_PROTOCOL: false}
      - run: dart pub run grinder pkg-standalone-dev
      - name: Run tests
        run: dart pub run test -r expanded

  deploy_github_linux:
    name: "Deploy Github: Linux"
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/') && github.repository == 'cyparu/dart-sass-embedded'"

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with: { version: "${{ env.protoc_version }}", repo-token: "${{ github.token }}" }
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart pub run grinder protobuf
      - name: Deploy
        run: dart pub run grinder pkg-github-release pkg-github-linux
        env: {GH_BEARER_TOKEN: "${{ github.token }}"}

