name: CI

env:
  protoc_version: '3.x'

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  deploy_github_linux:
    name: "Deploy Github: Linux"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with: { version: "${{ env.protoc_version }}", repo-token: "${{ github.token }}" }
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart pub run grinder protobuf
      - name: Deploy
        run: dart pub run grinder pkg-compile-native
        env: {GH_BEARER_TOKEN: "${{ github.token }}"}

